[package]
name = "auto-args"
version = "0.1.0"
authors = ["David Roundy <daveroundy@gmail.com>"]
edition = "2018"

[dependencies]
auto-args-derive =  { path = "auto-args-derive", version = "0.1.0" }
meval = "0.2.0"

[workspace]
